# Generated by Django 2.2.1 on 2019-05-23 11:31

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190521_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='/blog/static/blog/img/lifestyle.jpg', upload_to='picture_test'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_test',
            field=models.ImageField(blank=True, upload_to='my_post/images', verbose_name='blog title image'),
        ),
    ]
