# Generated by Django 2.2.1 on 2019-05-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190517_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
