# Generated by Django 2.2.1 on 2019-05-23 11:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190523_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/blog/static/blog/img/selfie.jpg', upload_to='my_post/images'),
        ),
    ]
