# Generated by Django 2.2.1 on 2019-05-23 15:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190523_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='/my_post/images/selfie.jpg', upload_to='my_category/images'),
        ),
    ]
